server:
  port: 60000

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://127.0.0.1:8888
  profiles:
    active: bus

#  security:
#    user:
#      name: user
#      password: $2a$10$g70rRcQBR7Jnm9A9m/Nqje8lCIPeADz2.VBMxhPyzUBoJc28pvC9.


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true


jwt:
  expiration: 86400000 #10 days
  secret: my-very-long-secret-key-1234567890123456

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
